services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=contacts'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=superuser'
    ports:
      - '5432:5432'

  server:
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres